server:
  port: 8766
spring:
  application:
    name: service-miya
  zipkin:
    base-url: http://192.168.1.100:9411
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/