server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zjline/SpringcloudConfig
          search-paths: respo
      label: master
eureka:
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/

